language: java
install: mvn clean install -DskipTests=true 
script: mvn test verify
branches:
  only:
    - master
jdk:
  - oraclejdk8
notifications:
  irc:
    - "irc.freenode.org#dynjs"
    - "irc.freenode.org#vertx"

